# Possible values: "critical", "high", "moderate", "low"
fail-on-severity: moderate
comment-summary-in-pr: always

# You can only include one of these two options: `allow-licenses` and `deny-licenses`
# ([String]). Only allow these licenses (optional)
# Possible values: Any `spdx_id` value(s) from https://docs.github.com/en/rest/licenses
allow-licenses:
  - MIT
  - GPL-3.0
  - BSD-3-Clause
# ([String]). Block the pull request on these licenses (optional)
# Possible values: Any  `spdx_id` value(s) from https://docs.github.com/en/rest/licenses
# deny-licenses:
#   - LGPL-2.0
#   - BSD-2-Clause

# ([String]). Skip these GitHub Advisory Database IDs during detection (optional)
# Possible values: Any valid GitHub Advisory Database ID from https://github.com/advisories
# allow-ghsas:
#   - GHSA-abcd-1234-5679
#   - GHSA-efgh-1234-5679

# ([String]). Block pull requests that introduce vulnerabilities in the scopes that match this list (optional)
# Possible values: "development", "runtime", "unknown"
fail-on-scopes:
  - development
  - runtime
  - unknown
