name: Run Checks

on:
  pull_request:
    branches:
      - main
  workflow_call: {}

permissions:
  actions: write
  contents: read
  security-events: write

env:
  CI: 1
  SITE_DIR: _site
  TETRIS_APP_HOST: "127.0.0.1"
  TETRIS_APP_PORT: "8080"
  TETRIS_APP_PATH: "pages/githubuniverseworkshops/github-devsecops-fundamentals"

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.ci.txt
      - name: Install NodeJS dependencies
        run: npm ci
      - name: Lint Python source
        run: |
          ruff check --format=github --select=E9,F63,F7,F82 --target-version=py311 .
  security-checks:
    runs-on: ubuntu-latest
    needs: run-checks
    steps:
      - uses: actions/checkout@v3
      - name: Run unit and integration tests
        run: npm test
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          config-file: >-
            ./.github/dependency-review-config.yml
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python,javascript
          setup-python-dependencies: "false"
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
